# Generated by Django 4.2.2 on 2023-06-27 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_profile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=250)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=user_profile.models.user_directory_path_avatar)),
                ('banner', models.ImageField(blank=True, null=True, upload_to=user_profile.models.user_directory_path_banner)),
                ('phone_no', models.CharField(blank=True, max_length=30)),
                ('about', models.TextField(blank=True, max_length=250)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
