# Generated by Django 4.2.2 on 2023-06-27 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_image', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimage',
            options={'verbose_name': 'PostImage', 'verbose_name_plural': 'PostImages'},
        ),
    ]
