# Generated by Django 4.2.2 on 2023-06-28 10:38

import django.core.validators
from django.db import migrations, models
import post_image.models


class Migration(migrations.Migration):

    dependencies = [
        ('post_image', '0002_alter_postimage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimage',
            options={'verbose_name': 'Upload', 'verbose_name_plural': 'Uploads'},
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=post_image.models.post_directory_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
    ]
