# Generated by Django 4.2.2 on 2023-06-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(blank=True, verbose_name='title'),
        ),
    ]
