# Generated by Django 4.2.2 on 2023-06-27 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friendrequest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='receiving_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendrequests_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='sending_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendrequests_sent', to=settings.AUTH_USER_MODEL),
        ),
    ]
