# Generated by Django 4.2.2 on 2023-06-28 12:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='follows_users',
        ),
        migrations.AddField(
            model_name='user',
            name='is_followed_by_users',
            field=models.ManyToManyField(blank=True, related_name='follows_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
