# Generated by Django 4.2.2 on 2023-06-29 09:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('email_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailscheduler',
            old_name='sender',
            new_name='from_email',
        ),
        migrations.RenameField(
            model_name='emailscheduler',
            old_name='body',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='emailscheduler',
            old_name='receiver_bcc',
            new_name='recipient_list',
        ),
        migrations.RenameField(
            model_name='emailscheduler',
            old_name='header',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='emailscheduler',
            name='receiver_cc',
        ),
        migrations.RemoveField(
            model_name='emailscheduler',
            name='receiver_to',
        ),
        migrations.AlterField(
            model_name='emailscheduler',
            name='scheduled_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
